apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: janwesterkamp-poi-backend-app-dev
  annotations:
    argocd/app-name: janwesterkamp-poi-backend-app-dev
    backstage.io/kubernetes-id: janwesterkamp-poi-backend-app
    backstage.io/kubernetes-namespace: janwesterkamp
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/janwesterkamp-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/janwesterkamp/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/janwesterkamp/deployments/janwesterkamp-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/janwesterkamp-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/janwesterkamp"
  system: workshop-system-janwesterkamp
  providesApis:
    - backend-api-janwesterkamp
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-janwesterkamp
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/janwesterkamp"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-janwesterkamp
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://janwesterkamp-poi-backend-app-janwesterkamp.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-demo/janwesterkamp-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/janwesterkamp"
  system: workshop-system-janwesterkamp
  definition:
    $text: https://github.com/rhdh23-demo/janwesterkamp-backend/tree/main/src/main/resources/META-INF/openapi.yaml
